# Generated by Django 2.2 on 2019-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
